import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserProviderFromProviders } from "@/providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayoutDashboard({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>

 

        {children}

  

        
        </body>
    </html>
  );
}
